# ===============================
# = PARAMETERS H2
# ===============================

# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      data-locations: classpath:data.sql # Especifica el archivo para datos iniciales
  data:
    rest:
      basePath: /api

# Configuración de logging
logging:
  level:
    root: INFO
  file:
    name: /Users/jgomez/temp/application.log
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss} - %logger{36} - %msg%n" # Patrón de logging para consola

# Configuración del servidor
server:
  port: 8080
