# ===============================
# = PARAMETERS H2
# ===============================

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver # Añadir el driver explícitamente
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    defer-datasource-initialization: false # Cambiar a false para que data.sql se cargue al iniciar
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always # Asegura que el script se ejecute siempre
      data-locations: classpath:data.sql # Archivo para datos iniciales, debe estar en src/main/resources
  data:
    rest:
      basePath: /api

# Configuración de logging
logging:
  level:
    root: INFO
  file:
    name: /Users/jgomez/temp/application.log
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

# Configuración del servidor
server:
  port: 8080
